[project]
name = "fake-openai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.122.0",
    "gunicorn>=23.0.0",
    "loguru>=0.7.3",
    "uvicorn>=0.38.0",
]
